// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1HM0WAp32KNN1eEpb-L9Pbjmad8VwRXk',
    appId: '1:990064075367:web:6b5be86212287ebf9e6ac2',
    messagingSenderId: '990064075367',
    projectId: 'hospitalmanagement-1f6c8',
    authDomain: 'hospitalmanagement-1f6c8.firebaseapp.com',
    storageBucket: 'hospitalmanagement-1f6c8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALH4LjaMVGwSdT9DjBG-9lW4mKJeyoSQE',
    appId: '1:990064075367:android:a825f87f2aa604249e6ac2',
    messagingSenderId: '990064075367',
    projectId: 'hospitalmanagement-1f6c8',
    storageBucket: 'hospitalmanagement-1f6c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKz_oczx9aZeFhI7jWo5L1r00ZSHrCX6g',
    appId: '1:990064075367:ios:c003eec19a1286759e6ac2',
    messagingSenderId: '990064075367',
    projectId: 'hospitalmanagement-1f6c8',
    storageBucket: 'hospitalmanagement-1f6c8.appspot.com',
    iosBundleId: 'com.example.doctorManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKz_oczx9aZeFhI7jWo5L1r00ZSHrCX6g',
    appId: '1:990064075367:ios:c003eec19a1286759e6ac2',
    messagingSenderId: '990064075367',
    projectId: 'hospitalmanagement-1f6c8',
    storageBucket: 'hospitalmanagement-1f6c8.appspot.com',
    iosBundleId: 'com.example.doctorManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1HM0WAp32KNN1eEpb-L9Pbjmad8VwRXk',
    appId: '1:990064075367:web:6604110016feff099e6ac2',
    messagingSenderId: '990064075367',
    projectId: 'hospitalmanagement-1f6c8',
    authDomain: 'hospitalmanagement-1f6c8.firebaseapp.com',
    storageBucket: 'hospitalmanagement-1f6c8.appspot.com',
  );
}
